name: Minedo
version: 1.0.0
main: net.minedo.mc.Minedo
description: A better Minecraft perhaps.
author: riazufila
api-version: "1.20"
commands:
  warp:
    description: "Warp to a region."
    usage: "/warp <region>"
  teleport:
    description: "Request teleport to a player and accept, decline, or discard a teleport request."
    usage: "/teleport <request <player> | accept | decline | discard>"
depend:
  - FastAsyncWorldEdit