name: Minedo
version: 1.0.0
main: io.github.riazufila.minedoplugin.Minedo
description: A better Minecraft perhaps.
author: riazufila
api-version: '1.20'
commands:
  spawn:
    description: "Teleport to spawn point."
    usage: "/spawn"
depend:
  - FastAsyncWorldEdit
  - WorldGuard