name: Minedo
version: 1.0.0
main: net.minedo.mc.Minedo
description: A better Minecraft perhaps.
author: riazufila
api-version: "1.20"

depend:
  - WorldEdit

permissions:
  minedo.command.warp:
    description: "Access to /warp command."

  minedo.command.teleport:
    description: "Access to /teleport command."

  minedo.command.narrate:
    description: "Access to /narrate command."

  minedo.command.like:
    description: "Access to /like command."

  minedo.command.ignore:
    description: "Access to /ignore command."

  minedo.command.message:
    description: "Access to /message command."

  minedo.group.default:
    description: "Default features."
    default: true
    children:
      - "minedo.command.warp"
      - "minedo.command.teleport"
      - "minedo.command.like"
      - "minedo.command.ignore"
      - "minedo.command.message"

  minedo.group.gold:
    description: "Allow access to Gold features, along with the defaults."
    children:
      - "minedo.group.default"

  minedo.group.emerald:
    description: "Allow access to Emerald features, along with Gold."
    children:
      - "minedo.group.gold"

  minedo.group.diamond:
    description: "Allow access to Diamond features, along with Emerald."
    children:
      - "minedo.group.emerald"

  minedo.group.redstone:
    description: "Allow access to Redstone features, along with Diamond."
    children:
      - "minedo.group.diamond"

  minedo.group.obsidian:
    description: "Allow access to Obsidian features, along with Redstone."
    children:
      - "minedo.group.redstone"
      - "minedo.command.narrate"

commands:
  warp:
    description: "Warp to a region."
    usage: "/warp <region>"
    permission: "minedo.command.warp"

  teleport:
    description: "Request teleport to a player and accept, decline, or discard a teleport request."
    usage: "/teleport <request <player> | accept | decline | discard>"
    permission: "minedo.command.teleport"

  narrate:
    description: "Broadcast a message as a narration."
    usage: "/narrate <message>"
    permission: "minedo.command.narrate"

  like:
    description: "Send player a like."
    usage: "/like <player>"
    permission: "minedo.command.like"

  ignore:
    description: "Ignore a player's chat, message, and teleport."
    usage: "/ignore <add | remove> <player>"
    permission: "minedo.command.ignore"

  message:
    description: "Message a player."
    usage: "/message <player>"
    permission: "minedo.command.message"
