name: Minedo
version: 1.0.0
main: net.minedo.mc.Minedo
description: A better Minecraft perhaps.
author: riazufila
api-version: "1.20"

depend:
  - FastAsyncWorldEdit

permissions:
  minedo.group.default:
    description: "Default features."
    default: true
  minedo.group.copper:
    description: "Allow access to Copper features, along with the defaults."
    children:
      - "minedo.group.default"
  minedo.group.iron:
    description: "Allow access to Iron features, along with Copper."
    children:
      - "minedo.group.copper"
  minedo.group.gold:
    description: "Allow access to Gold features, along with Iron."
    children:
      - "minedo.group.iron"
  minedo.group.diamond:
    description: "Allow access to Diamond features, along with Gold."
    children:
      - "minedo.group.gold"
  minedo.group.emerald:
    description: "Allow access to Emerald features, along with Diamond."
    children:
      - "minedo.group.diamond"
  minedo.group.obsidian:
    description: "Allow access to Obsidian features, along with Emerald."
    children:
      - "minedo.group.emerald"

commands:
  warp:
    description: "Warp to a region."
    usage: "/warp <region>"
    permission: "minedo.group.default"
  teleport:
    description: "Request teleport to a player and accept, decline, or discard a teleport request."
    usage: "/teleport <request <player> | accept | decline | discard>"
    permission: "minedo.group.default"
  debug:
    description: "Debug."
    usage: "/debug"
